### ISSUE TITLE
Improve Process of downloading a model

### ISSUE THREAD

**Issue by dtracers** [SaltieRL/Saltie#59]
Right now it should work but it needs to be tested and double checked on how it will work.
(Maybe see if we can make this work for the tournament too?)

And make sure that it works with the config options.

-------

Add ability of filtering/selecting one model to download from multiple possible models

**Comment by Sciguymjm** [comment]
Should this include filtering/selecting one to download from multiple possible models?

**Comment by dtracers** [comment]
yes that would be something I think we should add to that.

**Comment by Sciguymjm** [comment]
Model information will be stored alongside current model table, stored on disk similar to replays.

Issue updated.
